server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: drive
          uri: http://localhost:8081
          predicates:
            - Path=/files/**, 
        - id: indexing
          uri: http://localhost:8082
          predicates:
            - Path=/indices/**, 
        - id: videoprocessing
          uri: http://localhost:8083
          predicates:
            - Path=/videos/**, 
        - id: notification
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: dashboard
          uri: http://localhost:8085
          predicates:
            - Path=, /dashboards/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: drive
          uri: http://drive:8080
          predicates:
            - Path=/files/**, 
        - id: indexing
          uri: http://indexing:8080
          predicates:
            - Path=/indices/**, 
        - id: videoprocessing
          uri: http://videoprocessing:8080
          predicates:
            - Path=/videos/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, /dashboards/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
